name: Raika_bot_new
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3=1.40.39=pyhd8ed1ab_0
  - botocore=1.40.40=pyhd8ed1ab_0
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.8.3=h4c7d964_0
  - cffi=2.0.0=py310h29418f3_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - liblzma=5.8.1=h2466b09_2
  - libsqlite=3.50.4=hf5d6505_0
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.5.3=h725018a_1
  - pip=25.2=pyh8b19718_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.18=h8c5b53a_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=6_cp310
  - s3transfer=0.14.0=pyhd8ed1ab_0
  - six=1.17.0=pyhe01879c_1
  - tk=8.6.13=h2c6b04d_2
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_31
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - accelerate==1.10.1
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - async-timeout==4.0.3
      - attrs==25.3.0
      - audioread==3.0.1
      - beautifulsoup4==4.13.5
      - bidict==0.23.1
      - bitsandbytes==0.47.0
      - blis==0.7.11
      - brotli==1.1.0
      - bs4==0.0.2
      - catalogue==2.0.10
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.3.0
      - cloudpathlib==0.22.0
      - colorama==0.4.6
      - confection==0.1.5
      - configparser==7.2.0
      - coreferee==1.4.1
      - crcmod==1.7
      - cryptography==46.0.1
      - cymem==2.0.8
      - datasets==3.6.0
      - decorator==5.2.1
      - decord==0.6.0
      - dill==0.3.8
      - dnspython==2.8.0
      - editdistance==0.8.1
      - einops==0.8.1
      - en-core-web-sm==3.7.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - fastapi==0.117.1
      - ffmpy==0.6.1
      - filelock==3.13.1
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - funasr==1.2.7
      - gradio==5.47.2
      - gradio-client==1.13.3
      - greenlet==3.2.4
      - groovy==0.1.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.35.1
      - hydra-core==1.3.2
      - idna==3.10
      - inflect==7.5.0
      - jaconv==0.4.0
      - jamo==0.4.1
      - javalang==0.13.0
      - jieba==0.42.1
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kaldifst==1.7.17
      - kaldiio==2.18.1
      - langchain==0.3.27
      - langchain-core==0.3.76
      - langchain-text-splitters==0.3.11
      - langcodes==3.5.0
      - langgraph==0.6.7
      - langgraph-checkpoint==2.1.1
      - langgraph-prebuilt==0.6.4
      - langgraph-sdk==0.2.9
      - langsmith==0.4.31
      - language-data==1.3.0
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.45.0
      - lxml==6.0.2
      - marisa-trie==1.3.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - modelscope==1.30.0
      - more-itertools==10.8.0
      - motor==3.7.1
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.4
      - multiprocess==0.70.16
      - murmurhash==1.0.13
      - networkx==3.3
      - numba==0.62.0
      - numpy==1.26.4
      - omegaconf==2.3.0
      - openpyxl==3.1.5
      - orjson==3.11.3
      - ormsgpack==1.10.0
      - oss2==2.19.1
      - packaging==25.0
      - pandas==2.3.2
      - pathlib-abc==0.1.1
      - pathy==0.11.0
      - pillow==11.0.0
      - platformdirs==4.4.0
      - pooch==1.8.2
      - preshed==3.0.9
      - propcache==0.3.2
      - protobuf==3.20.3
      - psutil==5.9.8
      - pyarrow==21.0.0
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pymongo==4.15.1
      - pynndescent==0.5.13
      - pypdf2==3.0.1
      - python-docx==1.2.0
      - python-dotenv==1.1.1
      - python-engineio==4.12.2
      - python-multipart==0.0.20
      - python-socketio==5.13.0
      - pytorch-wpe==0.0.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - redis==6.4.0
      - regex==2025.9.18
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.1.0
      - ruff==0.13.2
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentence-transformers==5.1.1
      - sentencepiece==0.2.1
      - setuptools==80.9.0
      - shellingham==1.5.4
      - simple-websocket==1.1.0
      - simpleaudio==1.0.4
      - simplejson==3.20.2
      - smart-open==7.3.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile==0.13.1
      - soupsieve==2.8
      - soxr==1.0.0
      - spaces==0.42.1
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.43
      - srsly==2.5.1
      - starlette==0.48.0
      - sympy==1.13.3
      - tenacity==9.1.2
      - tensorboardx==2.6.4
      - thinc==8.2.5
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.19.1
      - tomlkit==0.13.3
      - torch==2.7.1+cu118
      - torch-complex==0.4.4
      - torchaudio==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - tqdm==4.67.1
      - transformers==4.41.2
      - typeguard==4.4.4
      - typer==0.19.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - uvicorn==0.37.0
      - voxcpm==1.0.4
      - wasabi==1.1.3
      - watchfiles==1.1.0
      - weasel==0.4.1
      - webencodings==0.5.1
      - websockets==15.0.1
      - wetext==0.1.0
      - wrapt==1.17.3
      - wsproto==1.2.0
      - xxhash==3.5.0
      - yarl==1.20.1
      - zstandard==0.25.0
prefix: C:\Users\User\anaconda3\envs\Raika_bot_new
