addict==2.4.0
annotated-types==0.7.0
anyio==4.11.0
async-timeout==5.0.1
certifi==2025.10.5
charset-normalizer==3.4.4
click==8.3.0
colorama==0.4.6
easydict==1.13
einops==0.8.1
exceptiongroup==1.3.0
fastapi==0.115.2
filelock==3.19.1
fsspec==2025.9.0
h11==0.16.0
httpcore==1.0.9
httptools==0.7.1
httpx==0.28.1
huggingface-hub==0.36.0
idna==3.11
Jinja2==3.1.6
MarkupSafe==2.1.5
mpmath==1.3.0
networkx==3.3
numpy==2.1.2
packaging==25.0
pdf2image==1.17.0
pillow==11.3.0
pydantic==2.12.4
pydantic_core==2.41.5
PyMuPDF==1.26.6
python-dotenv==1.2.1
python-multipart==0.0.20
PyYAML==6.0.3
redis==7.0.1
regex==2025.11.3
requests==2.32.5
safetensors==0.6.2
sniffio==1.3.1
starlette==0.40.0
sympy==1.13.1
tokenizers==0.20.3
torch==2.6.0+cu124
torchaudio==2.6.0+cu124
torchvision==0.21.0+cu124
tqdm==4.67.1
transformers==4.46.3
typing-inspection==0.4.2
typing_extensions==4.15.0
urllib3==2.5.0
uvicorn==0.30.6
watchfiles==1.1.1
websockets==15.0.1
